// Generated by gencpp from file rover_msgs/Battery_level.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_BATTERY_LEVEL_H
#define ROVER_MSGS_MESSAGE_BATTERY_LEVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct Battery_level_
{
  typedef Battery_level_<ContainerAllocator> Type;

  Battery_level_()
    : batt1(0.0)
    , batt2(0.0)
    , batt3(0.0)
    , batt(0)  {
    }
  Battery_level_(const ContainerAllocator& _alloc)
    : batt1(0.0)
    , batt2(0.0)
    , batt3(0.0)
    , batt(0)  {
  (void)_alloc;
    }



   typedef double _batt1_type;
  _batt1_type batt1;

   typedef double _batt2_type;
  _batt2_type batt2;

   typedef double _batt3_type;
  _batt3_type batt3;

   typedef int32_t _batt_type;
  _batt_type batt;




  typedef boost::shared_ptr< ::rover_msgs::Battery_level_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Battery_level_<ContainerAllocator> const> ConstPtr;

}; // struct Battery_level_

typedef ::rover_msgs::Battery_level_<std::allocator<void> > Battery_level;

typedef boost::shared_ptr< ::rover_msgs::Battery_level > Battery_levelPtr;
typedef boost::shared_ptr< ::rover_msgs::Battery_level const> Battery_levelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::Battery_level_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::Battery_level_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/aniket/URC_final/master/rover-control/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Battery_level_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Battery_level_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Battery_level_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Battery_level_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Battery_level_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Battery_level_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Battery_level_<ContainerAllocator> >
{
  static const char* value()
  {
    return "193ae58d2bb8491f232609244038c21e";
  }

  static const char* value(const ::rover_msgs::Battery_level_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x193ae58d2bb8491fULL;
  static const uint64_t static_value2 = 0x232609244038c21eULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Battery_level_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/Battery_level";
  }

  static const char* value(const ::rover_msgs::Battery_level_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Battery_level_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 batt1\n\
float64 batt2\n\
float64 batt3\n\
int32 batt\n\
";
  }

  static const char* value(const ::rover_msgs::Battery_level_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::Battery_level_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.batt1);
      stream.next(m.batt2);
      stream.next(m.batt3);
      stream.next(m.batt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Battery_level_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Battery_level_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::Battery_level_<ContainerAllocator>& v)
  {
    s << indent << "batt1: ";
    Printer<double>::stream(s, indent + "  ", v.batt1);
    s << indent << "batt2: ";
    Printer<double>::stream(s, indent + "  ", v.batt2);
    s << indent << "batt3: ";
    Printer<double>::stream(s, indent + "  ", v.batt3);
    s << indent << "batt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.batt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_BATTERY_LEVEL_H
