// Generated by gencpp from file rover_msgs/Enc.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_ENC_H
#define ROVER_MSGS_MESSAGE_ENC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct Enc_
{
  typedef Enc_<ContainerAllocator> Type;

  Enc_()
    : rpm_enc_1(0.0)
    , rpm_enc_2(0.0)  {
    }
  Enc_(const ContainerAllocator& _alloc)
    : rpm_enc_1(0.0)
    , rpm_enc_2(0.0)  {
  (void)_alloc;
    }



   typedef double _rpm_enc_1_type;
  _rpm_enc_1_type rpm_enc_1;

   typedef double _rpm_enc_2_type;
  _rpm_enc_2_type rpm_enc_2;




  typedef boost::shared_ptr< ::rover_msgs::Enc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Enc_<ContainerAllocator> const> ConstPtr;

}; // struct Enc_

typedef ::rover_msgs::Enc_<std::allocator<void> > Enc;

typedef boost::shared_ptr< ::rover_msgs::Enc > EncPtr;
typedef boost::shared_ptr< ::rover_msgs::Enc const> EncConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::Enc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::Enc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/aniket/URC_final/master/rover-control/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Enc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Enc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Enc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Enc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Enc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Enc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fc26589b8f906330b9bf64006152365";
  }

  static const char* value(const ::rover_msgs::Enc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fc26589b8f90633ULL;
  static const uint64_t static_value2 = 0x0b9bf64006152365ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/Enc";
  }

  static const char* value(const ::rover_msgs::Enc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rpm_enc_1\n\
float64 rpm_enc_2\n\
";
  }

  static const char* value(const ::rover_msgs::Enc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::Enc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rpm_enc_1);
      stream.next(m.rpm_enc_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Enc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Enc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::Enc_<ContainerAllocator>& v)
  {
    s << indent << "rpm_enc_1: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_enc_1);
    s << indent << "rpm_enc_2: ";
    Printer<double>::stream(s, indent + "  ", v.rpm_enc_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_ENC_H
