// Generated by gencpp from file rover_msgs/MPU.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_MPU_H
#define ROVER_MSGS_MESSAGE_MPU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct MPU_
{
  typedef MPU_<ContainerAllocator> Type;

  MPU_()
    : gyro_x(0.0)
    , gyro_y(0.0)
    , gyro_z(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)  {
    }
  MPU_(const ContainerAllocator& _alloc)
    : gyro_x(0.0)
    , gyro_y(0.0)
    , gyro_z(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)  {
  (void)_alloc;
    }



   typedef float _gyro_x_type;
  _gyro_x_type gyro_x;

   typedef float _gyro_y_type;
  _gyro_y_type gyro_y;

   typedef float _gyro_z_type;
  _gyro_z_type gyro_z;

   typedef float _acc_x_type;
  _acc_x_type acc_x;

   typedef float _acc_y_type;
  _acc_y_type acc_y;

   typedef float _acc_z_type;
  _acc_z_type acc_z;




  typedef boost::shared_ptr< ::rover_msgs::MPU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::MPU_<ContainerAllocator> const> ConstPtr;

}; // struct MPU_

typedef ::rover_msgs::MPU_<std::allocator<void> > MPU;

typedef boost::shared_ptr< ::rover_msgs::MPU > MPUPtr;
typedef boost::shared_ptr< ::rover_msgs::MPU const> MPUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::MPU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::MPU_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/achu/Documents/rover-control/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::MPU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::MPU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::MPU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::MPU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::MPU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::MPU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::MPU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c0239ab8497dbf714abae1bc9165695";
  }

  static const char* value(const ::rover_msgs::MPU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c0239ab8497dbf7ULL;
  static const uint64_t static_value2 = 0x14abae1bc9165695ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::MPU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/MPU";
  }

  static const char* value(const ::rover_msgs::MPU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::MPU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 gyro_x\n\
float32 gyro_y\n\
float32 gyro_z\n\
float32 acc_x\n\
float32 acc_y\n\
float32 acc_z\n\
";
  }

  static const char* value(const ::rover_msgs::MPU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::MPU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gyro_x);
      stream.next(m.gyro_y);
      stream.next(m.gyro_z);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MPU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::MPU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::MPU_<ContainerAllocator>& v)
  {
    s << indent << "gyro_x: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_x);
    s << indent << "gyro_y: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_y);
    s << indent << "gyro_z: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_z);
    s << indent << "acc_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_MPU_H
