// Generated by gencpp from file rover_msgs/SC_task.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_SC_TASK_H
#define ROVER_MSGS_MESSAGE_SC_TASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct SC_task_
{
  typedef SC_task_<ContainerAllocator> Type;

  SC_task_()
    : Atm_temp(0.0)
    , Atm_press(0.0)
    , Soil_humi(0.0)
    , Altitude(0.0)
    , Soil_temp(0.0)  {
    }
  SC_task_(const ContainerAllocator& _alloc)
    : Atm_temp(0.0)
    , Atm_press(0.0)
    , Soil_humi(0.0)
    , Altitude(0.0)
    , Soil_temp(0.0)  {
  (void)_alloc;
    }



   typedef double _Atm_temp_type;
  _Atm_temp_type Atm_temp;

   typedef double _Atm_press_type;
  _Atm_press_type Atm_press;

   typedef double _Soil_humi_type;
  _Soil_humi_type Soil_humi;

   typedef double _Altitude_type;
  _Altitude_type Altitude;

   typedef double _Soil_temp_type;
  _Soil_temp_type Soil_temp;




  typedef boost::shared_ptr< ::rover_msgs::SC_task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::SC_task_<ContainerAllocator> const> ConstPtr;

}; // struct SC_task_

typedef ::rover_msgs::SC_task_<std::allocator<void> > SC_task;

typedef boost::shared_ptr< ::rover_msgs::SC_task > SC_taskPtr;
typedef boost::shared_ptr< ::rover_msgs::SC_task const> SC_taskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::SC_task_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::SC_task_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/aniket/URC_final/master/rover-control/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::SC_task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::SC_task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::SC_task_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::SC_task_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::SC_task_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::SC_task_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::SC_task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b900671081180e4f2234b5fd31a35404";
  }

  static const char* value(const ::rover_msgs::SC_task_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb900671081180e4fULL;
  static const uint64_t static_value2 = 0x2234b5fd31a35404ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::SC_task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/SC_task";
  }

  static const char* value(const ::rover_msgs::SC_task_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::SC_task_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Atm_temp\n\
float64 Atm_press\n\
float64 Soil_humi\n\
float64 Altitude\n\
float64 Soil_temp\n\
";
  }

  static const char* value(const ::rover_msgs::SC_task_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::SC_task_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Atm_temp);
      stream.next(m.Atm_press);
      stream.next(m.Soil_humi);
      stream.next(m.Altitude);
      stream.next(m.Soil_temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SC_task_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::SC_task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::SC_task_<ContainerAllocator>& v)
  {
    s << indent << "Atm_temp: ";
    Printer<double>::stream(s, indent + "  ", v.Atm_temp);
    s << indent << "Atm_press: ";
    Printer<double>::stream(s, indent + "  ", v.Atm_press);
    s << indent << "Soil_humi: ";
    Printer<double>::stream(s, indent + "  ", v.Soil_humi);
    s << indent << "Altitude: ";
    Printer<double>::stream(s, indent + "  ", v.Altitude);
    s << indent << "Soil_temp: ";
    Printer<double>::stream(s, indent + "  ", v.Soil_temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_SC_TASK_H
