// Generated by gencpp from file rover_msgs/WheelVelPower.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_WHEELVELPOWER_H
#define ROVER_MSGS_MESSAGE_WHEELVELPOWER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct WheelVelPower_
{
  typedef WheelVelPower_<ContainerAllocator> Type;

  WheelVelPower_()
    : left_front_vel(0.0)
    , right_front_vel(0.0)
    , left_middle_vel(0.0)
    , right_middle_vel(0.0)
    , left_back_vel(0.0)
    , right_back_vel(0.0)
    , power_1(0.0)
    , power_2(0.0)
    , power_3(0.0)  {
    }
  WheelVelPower_(const ContainerAllocator& _alloc)
    : left_front_vel(0.0)
    , right_front_vel(0.0)
    , left_middle_vel(0.0)
    , right_middle_vel(0.0)
    , left_back_vel(0.0)
    , right_back_vel(0.0)
    , power_1(0.0)
    , power_2(0.0)
    , power_3(0.0)  {
  (void)_alloc;
    }



   typedef double _left_front_vel_type;
  _left_front_vel_type left_front_vel;

   typedef double _right_front_vel_type;
  _right_front_vel_type right_front_vel;

   typedef double _left_middle_vel_type;
  _left_middle_vel_type left_middle_vel;

   typedef double _right_middle_vel_type;
  _right_middle_vel_type right_middle_vel;

   typedef double _left_back_vel_type;
  _left_back_vel_type left_back_vel;

   typedef double _right_back_vel_type;
  _right_back_vel_type right_back_vel;

   typedef double _power_1_type;
  _power_1_type power_1;

   typedef double _power_2_type;
  _power_2_type power_2;

   typedef double _power_3_type;
  _power_3_type power_3;




  typedef boost::shared_ptr< ::rover_msgs::WheelVelPower_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::WheelVelPower_<ContainerAllocator> const> ConstPtr;

}; // struct WheelVelPower_

typedef ::rover_msgs::WheelVelPower_<std::allocator<void> > WheelVelPower;

typedef boost::shared_ptr< ::rover_msgs::WheelVelPower > WheelVelPowerPtr;
typedef boost::shared_ptr< ::rover_msgs::WheelVelPower const> WheelVelPowerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::WheelVelPower_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::WheelVelPower_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/aniket/URC_final/master/rover-control/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::WheelVelPower_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::WheelVelPower_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::WheelVelPower_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f13c06ab7a6186260b614a9e977d02cb";
  }

  static const char* value(const ::rover_msgs::WheelVelPower_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf13c06ab7a618626ULL;
  static const uint64_t static_value2 = 0x0b614a9e977d02cbULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/WheelVelPower";
  }

  static const char* value(const ::rover_msgs::WheelVelPower_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_front_vel\n\
float64 right_front_vel\n\
float64 left_middle_vel\n\
float64 right_middle_vel\n\
float64 left_back_vel\n\
float64 right_back_vel\n\
float64 power_1\n\
float64 power_2\n\
float64 power_3\n\
\n\
";
  }

  static const char* value(const ::rover_msgs::WheelVelPower_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_front_vel);
      stream.next(m.right_front_vel);
      stream.next(m.left_middle_vel);
      stream.next(m.right_middle_vel);
      stream.next(m.left_back_vel);
      stream.next(m.right_back_vel);
      stream.next(m.power_1);
      stream.next(m.power_2);
      stream.next(m.power_3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelVelPower_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::WheelVelPower_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::WheelVelPower_<ContainerAllocator>& v)
  {
    s << indent << "left_front_vel: ";
    Printer<double>::stream(s, indent + "  ", v.left_front_vel);
    s << indent << "right_front_vel: ";
    Printer<double>::stream(s, indent + "  ", v.right_front_vel);
    s << indent << "left_middle_vel: ";
    Printer<double>::stream(s, indent + "  ", v.left_middle_vel);
    s << indent << "right_middle_vel: ";
    Printer<double>::stream(s, indent + "  ", v.right_middle_vel);
    s << indent << "left_back_vel: ";
    Printer<double>::stream(s, indent + "  ", v.left_back_vel);
    s << indent << "right_back_vel: ";
    Printer<double>::stream(s, indent + "  ", v.right_back_vel);
    s << indent << "power_1: ";
    Printer<double>::stream(s, indent + "  ", v.power_1);
    s << indent << "power_2: ";
    Printer<double>::stream(s, indent + "  ", v.power_2);
    s << indent << "power_3: ";
    Printer<double>::stream(s, indent + "  ", v.power_3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_WHEELVELPOWER_H
