// Generated by gencpp from file rover_msgs/WheelVelocity.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_WHEELVELOCITY_H
#define ROVER_MSGS_MESSAGE_WHEELVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct WheelVelocity_
{
  typedef WheelVelocity_<ContainerAllocator> Type;

  WheelVelocity_()
    : left(0.0)
    , right(0.0)
    , reset_flag(0)  {
    }
  WheelVelocity_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)
    , reset_flag(0)  {
  (void)_alloc;
    }



   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;

   typedef int16_t _reset_flag_type;
  _reset_flag_type reset_flag;




  typedef boost::shared_ptr< ::rover_msgs::WheelVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::WheelVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct WheelVelocity_

typedef ::rover_msgs::WheelVelocity_<std::allocator<void> > WheelVelocity;

typedef boost::shared_ptr< ::rover_msgs::WheelVelocity > WheelVelocityPtr;
typedef boost::shared_ptr< ::rover_msgs::WheelVelocity const> WheelVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::WheelVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::WheelVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/aniket/URC_final/master/rover-control/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::WheelVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::WheelVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::WheelVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22c56d70a0f2060151657bd9cd98512f";
  }

  static const char* value(const ::rover_msgs::WheelVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22c56d70a0f20601ULL;
  static const uint64_t static_value2 = 0x51657bd9cd98512fULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/WheelVelocity";
  }

  static const char* value(const ::rover_msgs::WheelVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left\n\
float64 right\n\
int16 reset_flag\n\
\n\
";
  }

  static const char* value(const ::rover_msgs::WheelVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.reset_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::WheelVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::WheelVelocity_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
    s << indent << "reset_flag: ";
    Printer<int16_t>::stream(s, indent + "  ", v.reset_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_WHEELVELOCITY_H
