# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_msgs/GripperMotion.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GripperMotion(genpy.Message):
  _md5sum = "8edaeaec64be0c5d3ae535eef1f2c3ef"
  _type = "rover_msgs/GripperMotion"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool button_1
bool button_2
bool button_3
bool button_4
bool button_5
bool button_6

"""
  __slots__ = ['button_1','button_2','button_3','button_4','button_5','button_6']
  _slot_types = ['bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       button_1,button_2,button_3,button_4,button_5,button_6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripperMotion, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.button_1 is None:
        self.button_1 = False
      if self.button_2 is None:
        self.button_2 = False
      if self.button_3 is None:
        self.button_3 = False
      if self.button_4 is None:
        self.button_4 = False
      if self.button_5 is None:
        self.button_5 = False
      if self.button_6 is None:
        self.button_6 = False
    else:
      self.button_1 = False
      self.button_2 = False
      self.button_3 = False
      self.button_4 = False
      self.button_5 = False
      self.button_6 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6B.pack(_x.button_1, _x.button_2, _x.button_3, _x.button_4, _x.button_5, _x.button_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.button_1, _x.button_2, _x.button_3, _x.button_4, _x.button_5, _x.button_6,) = _struct_6B.unpack(str[start:end])
      self.button_1 = bool(self.button_1)
      self.button_2 = bool(self.button_2)
      self.button_3 = bool(self.button_3)
      self.button_4 = bool(self.button_4)
      self.button_5 = bool(self.button_5)
      self.button_6 = bool(self.button_6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6B.pack(_x.button_1, _x.button_2, _x.button_3, _x.button_4, _x.button_5, _x.button_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.button_1, _x.button_2, _x.button_3, _x.button_4, _x.button_5, _x.button_6,) = _struct_6B.unpack(str[start:end])
      self.button_1 = bool(self.button_1)
      self.button_2 = bool(self.button_2)
      self.button_3 = bool(self.button_3)
      self.button_4 = bool(self.button_4)
      self.button_5 = bool(self.button_5)
      self.button_6 = bool(self.button_6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6B = struct.Struct("<6B")
