# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_msgs/SC_task.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SC_task(genpy.Message):
  _md5sum = "b900671081180e4f2234b5fd31a35404"
  _type = "rover_msgs/SC_task"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 Atm_temp
float64 Atm_press
float64 Soil_humi
float64 Altitude
float64 Soil_temp
"""
  __slots__ = ['Atm_temp','Atm_press','Soil_humi','Altitude','Soil_temp']
  _slot_types = ['float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Atm_temp,Atm_press,Soil_humi,Altitude,Soil_temp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SC_task, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Atm_temp is None:
        self.Atm_temp = 0.
      if self.Atm_press is None:
        self.Atm_press = 0.
      if self.Soil_humi is None:
        self.Soil_humi = 0.
      if self.Altitude is None:
        self.Altitude = 0.
      if self.Soil_temp is None:
        self.Soil_temp = 0.
    else:
      self.Atm_temp = 0.
      self.Atm_press = 0.
      self.Soil_humi = 0.
      self.Altitude = 0.
      self.Soil_temp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.Atm_temp, _x.Atm_press, _x.Soil_humi, _x.Altitude, _x.Soil_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.Atm_temp, _x.Atm_press, _x.Soil_humi, _x.Altitude, _x.Soil_temp,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5d.pack(_x.Atm_temp, _x.Atm_press, _x.Soil_humi, _x.Altitude, _x.Soil_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.Atm_temp, _x.Atm_press, _x.Soil_humi, _x.Altitude, _x.Soil_temp,) = _struct_5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5d = struct.Struct("<5d")
