(cl:defpackage rover_msgs-msg
  (:use )
  (:export
   "<WHEELVELPOWER>"
   "WHEELVELPOWER"
   "<POWER>"
   "POWER"
   "<SC_TASK>"
   "SC_TASK"
   "<BATTERY_LEVEL>"
   "BATTERY_LEVEL"
   "<DIGGER>"
   "DIGGER"
   "<ARM>"
   "ARM"
   "<GRIPPERMOTION>"
   "GRIPPERMOTION"
   "<GPS>"
   "GPS"
   "<ARMANGLE>"
   "ARMANGLE"
   "<ENC>"
   "ENC"
   "<ROUTERANGLE>"
   "ROUTERANGLE"
   "<MPU>"
   "MPU"
   "<CAMERAMOTION>"
   "CAMERAMOTION"
   "<WHEELVELOCITY>"
   "WHEELVELOCITY"
  ))

