(cl:in-package rover_msgs-msg)
(cl:export '(ORIENTATION-VAL
          ORIENTATION
          ORIENTATION_COVARIANCE-VAL
          ORIENTATION_COVARIANCE
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          ANGULAR_VELOCITY_COVARIANCE-VAL
          ANGULAR_VELOCITY_COVARIANCE
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          LINEAR_ACCELERATION_COVARIANCE-VAL
          LINEAR_ACCELERATION_COVARIANCE
))