(cl:in-package rover_msgs-msg)
(cl:export '(POWER_1-VAL
          POWER_1
          POWER_2-VAL
          POWER_2
          POWER_3-VAL
          POWER_3
          POWER_4-VAL
          POWER_4
          POWER_5-VAL
          POWER_5
          POWER_6-VAL
          POWER_6
          POWER_7-VAL
          POWER_7
          BAT1-VAL
          BAT1
          BAT2-VAL
          BAT2
          BAT3-VAL
          BAT3
          BAT4-VAL
          BAT4
          BAT5-VAL
          BAT5
          BAT6-VAL
          BAT6
          BAT7-VAL
          BAT7
))